[project]
name = "mindset-growth"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "streamlit>=1.44.1",
]
[tool.poetry]
package-mode = false
